apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: veilarbdetaljerfs
  namespace: obo
  labels:
    team: obo
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.08.30_10.15-9c1569b22e37
  port: 8080
  ingresses:
    - https://veilarbdetaljer.intern.dev.nav.no
    - https://veilarbdetaljer.ansatt.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: obo-veilarbdetaljerfs-dev
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "cors": {
            "origin": [
              "https://veilarbpersonflate.intern.dev.nav.no",
              "https://veilarbpersonflate.ansatt.dev.nav.no"
            ]
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no"]
             },
            "corp": {
            "policy": "cross-origin"
             }
          },
          "gcs": {
            "bucketName": "obo-veilarbdetaljerfs-dev"
          }
        }
