apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: veilarbdetaljerfs
  namespace: obo
  labels:
    team: obo
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.07.24_08.48-0eb05ecdf7ea
  port: 8080
  ingresses:
    - https://veilarbdetaljer.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: obo-veilarbdetaljerfs-prod
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "cors": {
            "origin": "https://veilarbpersonflate.intern.nav.no"
          },
          "gcs": {
            "bucketName": "obo-veilarbdetaljerfs-prod"
          }
        }
